### ISSUE TITLE
Demo - Personnas

### ISSUE THREAD

**Issue by XxMaexX** [MTM6330-F18/Final-LEAFS#3]

**Comment by XxMaexX** [comment]
personna#01 - primary

Name: Maria Paperman
Age: 17 years old
Gender: Female
Status: High school graduate
Target audience: Primary

Technology level: 
Quite good with technological devices, has already created her own website, knows the basic of coding
Lifestyles/Hobbies: codes during spare time, doesn’t go outside that often, always on time, photographs landscapes or portrait, sketch a few designs on her notebook
Likes/Dislikes: 
enjoys reading, sketching and photographing
dislikes outdoor activities, cold weathers, polluted areas 
Goals: 
needs to find specific information regarding to their search
Task: 
to be able to find any information regarding to a professor in the program, know the outcome a program would provide her, learn about the program and school
Motivation: 
Maria wants to be sure that she has all important information about the program. She will then ask the professors how the classes are going to function and what are the outcome to them since Maria just graduated high school. 
Frustration: 
has a hard time understanding new content, non-functional tools when editing on the computer

link is to our google drive: https://docs.google.com/document/d/1FzD2Spb6DWJSfyFPKEmBfkgON8fklnbuumhmGFguGqg/edit

**Comment by VinciLin** [comment]
personna#01 - primary

Name: Zhixin Ji 
Age: 26
Gender: Female
Target audience: Primary

“I love design and photograph. I want to come out of my comfort zone. Change my career path. ”

Zhixin Ji is an international student, who has 2 years Retail industry work experience after her bachelor degree

**Motivators:**
Her Career - She has an broadcast relative bachelor degree. However she works in retail for about 2 years. She is really bored with this industry. She wants to do some relative to her bachelor program and to discover her own passion points deeper.
Her Life - She wants to experience living in another country and become more cultured. The idea of living in Canada, or anywhere, is very appealing to her.

**Goal:**
Zhixin wants to know if the Interactive media design program is the best choice for her. She has some concerns about what the real status after graduation will be and how about the employment rate. She is not confident enough of her English communication skill.
