### ISSUE TITLE
Question for Micheal 

### ISSUE THREAD

**Issue by XxMaexX** [MTM6330-F18/Final-LEAFS#4]

**Comment by VinciLin** [comment]
I have some questions already, pls leave your comments for more or revision.

**Questions:**

1. Expert area
2. Their Experience
3. Share one of their best student experience

**Comment by XxMaexX** [comment]
ask also...
- work advice
- courses taught
- why he/she came to Algonquin College

**Comment by VinciLin** [comment]
**Answers From Micheal:**

What courses do you teach?
I am teach Client-Side Web Development and Server-Side Web Development for the IMD program.

Your Background / Experience
I created my first web site in 1997 and continue to do web development as a hobby until my first web development job in 2006. I am largely self-taught and have receive very little formal training in web development. In 2016, after 10 years working professionally in the industry, I started teaching at Algonquin college.  

Why do you come to Algonquin College?
The field of web design and development is ever-changing and if you don’t keep moving, you will fall behind. It is this realization that lead me to start teaching at Algonquin College in January of 2016. I have a passion for learning and it fuels my desire to share what I know with others. It has become my new passion, and my primary focus. I aim to be the best teacher I can, and it is my hope that my students will find the same spark of curiosity that changed my life all those years ago. 

Could you share one of your best student experience?
I once had a student who was struggling in my class to the point that she was going to fail. I offered to help her outside of class, and she agreed. We continued to meet on a weekly basis. By the end of the term, not only did she have a passing grade, but she understood the material and was helping others.

Could you give some Work advice for future IMD students?
Never stop learning. The web development industry is constantly moving and changing, and those individuals you can adapt quickly will be the most successful.
