### ISSUE TITLE
Information needed about professors

### ISSUE THREAD

**Issue by XxMaexX** [MTM6330-F18/Final-LEAFS#7]
Basic information:
- what courses they've been teaching
- How many years they've work at Algonquin College
- Who they are? like roles, about them, etc.

**Comment by siqi107** [comment]
https://drive.google.com/drive/folders/16lAZT1ae2aprIvnGX1KSi_ndkhAkhJ4z

**Comment by siqi107** [comment]
https://drive.google.com/drive/folders/16lAZT1ae2aprIvnGX1KSi_ndkhAkhJ4z
